version: '2.1' 
services:
  namenode:
    image: namenode
    container_name: namenode
    networks:
     - lab
    volumes:
      - ./data/namenode:/hadoop/dfs/name
      - ./data/home:/home/jovyan
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env
    ports:
      - 50070:50070
      - 8020:8020
    mem_limit: 1G
  jupyter-pyspark:
    image: jpyspark
    container_name: jupyter
    env_file:
      - ./hadoop.env
    ports:
      - 8888:8888
      - 8000:8000
      - 4040:4040
    networks:
      - lab
    volumes:
      - ./data/LocalHome/:/home/
    environment:
      - JUPYTER_ENABLE_LAB=yes
    mem_limit: 3G
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 5432:5432
    networks:
      lab:
        ipv4_address: 172.23.0.2
    volumes:
      - ./data/postgres/:/var/lib/postgresql/data
    mem_limit: 512M
networks:
  lab:
    driver: bridge
