version: '3' 
services:
  namenode:
    image: bde2020/hadoop-namenode:1.1.0-hadoop2.8-java8
    container_name: namenode
    networks:
     - nf_lab
    volumes:
      - ./data/namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env
    ports:
      - 50070:50070
      - 8020:8020
  datanode:
    image: bde2020/hadoop-datanode:1.1.0-hadoop2.8-java8
    depends_on: 
      - namenode
    networks: 
      - nf_lab
    volumes:
      - ./data/datanode:/hadoop/dfs/data
    env_file:
      - ./hadoop.env
    ports:
      - 50075:50075
      - 50010:50010
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 5432:5432
    networks:
      - nf_lab
    volumes:
      - ./data/postgres/:/var/lib/postgresql/data
  nifi:
    image: apache/nifi
    container_name: nifi
    volumes:
      - ./data/nifi/:/home/nifi
    networks:
      - nf_lab
    ports:
      - 8080:8080
  jupyter-pyspark:
    image: jupyter/pyspark-notebook
    container_name: jupyter
    env_file:
      - ./hadoop.env
    ports:
      - 8888:8888
    networks:
      - nf_lab
    volumes:
      - ./data/jupyter/:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes

networks:
  nf_lab:
    driver: bridge
