version: '3' 
services:
  namenode:
    image: namenode
    container_name: namenode
    networks:
     - lab
    volumes:
      - ./data/namenode:/hadoop/dfs/name
      - ./data/home:/home/jovyan
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env
    ports:
      - 50070:50070
      - 8020:8020
  jupyter-pyspark:
    image: jupyterlab-pyspark-git
    container_name: jupyter
    env_file:
      - ./hadoop.env
    ports:
      - 8888:8888
      - 4040:4040
    networks:
      - lab
    volumes:
      - ./data/jupyter/:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 5432:5432
    networks:
      - lab
    volumes:
      - ./data/postgres/:/var/lib/postgresql/data
networks:
  lab:
    name: Spark
    driver: bridge
